import { describe, expect, it } from 'vitest';
import { serializeConfig } from '../src/cli/json.js';
import { maskApiKey, inferProviderFromApiKey, isLikelyApiKey } from '../src/ai/provider.js';
import { getProviderStatus } from '../src/ai/provider.js';
import type { ICloserConfig, ProjectIdentity } from '../src/types.js';

const mockIdentity: ProjectIdentity = {
  language: 'typescript',
  framework: 'unknown',
  database: 'unknown',
  buildSystem: 'npm',
  testFramework: 'vitest',
  runtime: '>=18.0.0',
  deploymentType: 'unknown',
  packageManager: 'npm',
  languageVersion: 'unknown',
};

function makeConfig(overrides: Partial<ICloserConfig['ai']> = {}): ICloserConfig {
  return {
    version: '0.1.0',
    project: { name: 'test', rootPath: '/tmp/test', identity: mockIdentity },
    ai: {
      provider: 'mock',
      model: 'mock-offline',
      maxTokens: 100000,
      temperature: 0.3,
      ...overrides,
    },
    execution: { defaultMode: 'preview', maxRetries: 3, maxParallelTasks: 3, verifyStages: ['compile', 'lint', 'unit-test'] },
    security: { sensitiveFiles: [], dangerousCommands: [], disabledRules: [], allowGitPush: false },
    skills: { enabled: [], autoGenerated: false },
    memory: { maxProjectMemory: 10240, maxGlobalMemory: 51200, autoCompressThreshold: 50 },
  };
}

describe('JSON safety', () => {
  it('serializeConfig never includes apiKey', () => {
    const config = makeConfig({ provider: 'deepseek', model: 'deepseek-v4-pro', apiKey: 'sk-secret-1234567890abcdef' });
    const result = serializeConfig(config);

    // ai section must not have apiKey
    expect(result.ai).not.toHaveProperty('apiKey');
    expect(JSON.stringify(result)).not.toContain('sk-secret');
    expect(JSON.stringify(result)).not.toContain('apiKey');
  });

  it('serializeConfig ai section has provider/model/ready/keySource but no apiKey', () => {
    const config = makeConfig({ provider: 'openai', model: 'gpt-4o' });
    const result = serializeConfig(config);

    expect(result.ai.provider).toBe('openai');
    expect(result.ai.model).toBe('gpt-4o');
    expect(typeof result.ai.ready).toBe('boolean');
    expect(['config', 'env', 'missing', 'not-required']).toContain(result.ai.keySource);
    expect(result.ai.requiresApiKey).toBe(true);
    expect(Array.isArray(result.ai.envVars)).toBe(true);
    expect(Object.keys(result.ai)).not.toContain('apiKey');
  });

  it('serializeConfig for mock shows not-required', () => {
    const config = makeConfig({ provider: 'mock', model: 'mock-offline' });
    const result = serializeConfig(config);
    expect(result.ai.keySource).toBe('not-required');
    expect(result.ai.ready).toBe(true);
    expect(result.ai.requiresApiKey).toBe(false);
    expect(result.ai.envVars).toEqual([]);
  });
});

describe('maskApiKey', () => {
  it('masks long keys to prefix...suffix format', () => {
    const masked = maskApiKey('sk-1234567890abcdef1234567890abcdef');
    expect(masked).toBe('sk-123...cdef');
    expect(masked).not.toContain('7890abcdef12345678');
  });

  it('masks keys starting with sk-ant-', () => {
    const masked = maskApiKey('sk-ant-test12345678901234567890abcd');
    expect(masked).toMatch(/^sk-ant...[-a-z0-9]{4}$/);
  });

  it('masks keys starting with dashscope-', () => {
    const masked = maskApiKey('dashscope-test-key-12345678');
    expect(masked).toMatch(/^dashs/); // prefix preserved
    expect(masked).toContain('...');  // middle masked
    expect(masked).not.toBe('dashscope-test-key-12345678');
  });

  it('returns all asterisks for very short keys', () => {
    const masked = maskApiKey('ab');
    expect(masked).toBe('****');
  });

  it('masked key does not contain the original key', () => {
    const original = 'sk-or-abcdefghijklmnopqrstuvwxyz';
    const masked = maskApiKey(original);
    // The masked key should not be the same as the original
    expect(masked).not.toBe(original);
    // The long middle part should be absent
    expect(masked).not.toContain('ghijklmnopqrst');
  });
});

describe('inferProviderFromApiKey', () => {
  it('infers claude from sk-ant- prefix', () => {
    expect(inferProviderFromApiKey('sk-ant-test1234567890abcdef')).toBe('claude');
  });

  it('infers openai from sk-or- prefix', () => {
    expect(inferProviderFromApiKey('sk-or-test1234567890abcdef')).toBe('openai');
  });

  it('infers qwen from dashscope- prefix', () => {
    expect(inferProviderFromApiKey('dashscope-test-key-12345678')).toBe('qwen');
  });

  it('infers qwen from qwen- prefix', () => {
    expect(inferProviderFromApiKey('qwen-test-key-12345678')).toBe('qwen');
  });

  it('infers qwen from ak- prefix', () => {
    expect(inferProviderFromApiKey('ak-test-key-1234567890')).toBe('qwen');
  });

  it('falls back to deepseek for unrecognized prefixes', () => {
    expect(inferProviderFromApiKey('sk-unknown-prefix-key-12345')).toBe('deepseek');
  });

  it('uses custom fallback provider', () => {
    expect(inferProviderFromApiKey('sk-unknown', 'claude')).toBe('claude');
  });

  it('returns deepseek when fallback is mock', () => {
    expect(inferProviderFromApiKey('sk-unknown', 'mock')).toBe('deepseek');
  });
});

describe('isLikelyApiKey', () => {
  it('recognizes sk- prefixed keys', () => {
    expect(isLikelyApiKey('sk-1234567890abcdef1234567890abcdef')).toBe(true);
  });

  it('recognizes sk-ant- prefixed keys', () => {
    expect(isLikelyApiKey('sk-ant-test1234567890')).toBe(true);
  });

  it('recognizes dashscope- prefixed keys', () => {
    expect(isLikelyApiKey('dashscope-test-key-12345678')).toBe(true);
  });

  it('rejects values with spaces', () => {
    expect(isLikelyApiKey('sk-123 456')).toBe(false);
  });

  it('rejects short strings', () => {
    expect(isLikelyApiKey('sk-abc')).toBe(false);
  });

  it('rejects non-key strings like task descriptions', () => {
    expect(isLikelyApiKey('帮我给登录模块加手机号验证')).toBe(false);
  });
});

describe('getProviderStatus with config key', () => {
  it('reports keySource=config when apiKey is in config', () => {
    const status = getProviderStatus({
      provider: 'deepseek',
      model: 'deepseek-v4-pro',
      apiKey: 'sk-fake-1234567890abcdef',
      maxTokens: 100000,
      temperature: 0.3,
    });
    expect(status.ready).toBe(true);
    expect(status.keySource).toBe('config');
  });

  it('reports keySource=missing when no key in config or env', () => {
    const status = getProviderStatus({
      provider: 'openai',
      model: 'gpt-4o',
      maxTokens: 100000,
      temperature: 0.3,
    });
    // Without OPENAI_API_KEY in env and no apiKey in config
    expect(status.keySource).toBe('missing');
    expect(status.ready).toBe(false);
  });

  it('reports keySource=config for provider with explicit apiKey even if env is missing', () => {
    const status = getProviderStatus({
      provider: 'claude',
      model: 'claude-sonnet-4-6',
      apiKey: 'sk-ant-fake1234567890abcdef',
      maxTokens: 100000,
      temperature: 0.3,
    });
    expect(status.ready).toBe(true);
    expect(status.keySource).toBe('config');
  });
});

describe('config provider/model defaults', () => {
  it('mock is never overwritten by global defaults', () => {
    // Simulate: global config has deepseek, but project config has mock
    // The project config's provider should win
    const projectConfig = makeConfig({ provider: 'mock', model: 'mock-offline' });
    const globalConfig = { ai: { provider: 'deepseek', model: 'deepseek-v4-pro', apiKey: 'sk-1234567890abcdef' } };

    // loadConfig logic: when config.ai.provider is 'mock', global key should NOT override
    // The config merging ensures mock stays mock
    const mergedAI = globalConfig.ai.apiKey && projectConfig.ai.provider !== 'mock'
      ? { ...projectConfig.ai, ...globalConfig.ai }
      : { ...globalConfig.ai, ...projectConfig.ai };

    expect(mergedAI.provider).toBe('mock');
    expect(mergedAI.model).toBe('mock-offline');
  });

  it('real provider w/o key inherits global config', () => {
    const projectConfig = makeConfig({ provider: 'deepseek', model: 'deepseek-v4-pro' });
    delete projectConfig.ai.apiKey;
    const globalConfig = { ai: { provider: 'deepseek', model: 'deepseek-v4-pro', apiKey: 'sk-global-key-12345' } };

    const mergedAI = globalConfig.ai.apiKey && projectConfig.ai.provider !== 'mock'
      ? { ...projectConfig.ai, ...globalConfig.ai }
      : { ...globalConfig.ai, ...projectConfig.ai };

    expect(mergedAI.provider).toBe('deepseek');
    expect(mergedAI.apiKey).toBe('sk-global-key-12345');
  });
});
