// Configuration management for iCloser Agent Shell
import * as path from 'path';
import { fileExists, readJson, writeJson, ensureDir } from './utils/fs.js';
import type { ICloserConfig, ProjectIdentity, AIProvider, VerifyStage } from './types.js';

const CONFIG_FILENAME = 'icloser.json';
const GLOBAL_CONFIG_DIR = process.env.ICLOSER_HOME || path.join(
  process.env.HOME || process.env.USERPROFILE || '~',
  '.icloser'
);
const GLOBAL_CONFIG_PATH = path.join(GLOBAL_CONFIG_DIR, 'config.json');

export function defaultConfig(rootPath: string, identity: ProjectIdentity): ICloserConfig {
  const isFrontend = ['react', 'vue', 'nextjs', 'nuxt', 'svelte', 'angular'].includes(identity.framework);
  const isBackend = ['django', 'flask', 'fastapi', 'spring-boot', 'gin', 'actix', 'express', 'nestjs', 'laravel', 'rails'].includes(identity.framework);
  const provider = (process.env.ICLOSER_AI_PROVIDER as AIProvider) || 'claude';
  const defaultModels: Record<AIProvider, string> = {
    claude: 'claude-sonnet-4-6',
    deepseek: 'deepseek-v4-pro',
    openai: 'gpt-4o',
    qwen: 'qwen-max',
    mock: 'mock-offline',
  };

  return {
    version: '0.1.0',
    project: {
      name: path.basename(rootPath),
      rootPath,
      identity,
    },
    ai: {
      provider,
      model: defaultModels[provider] || defaultModels.claude,
      maxTokens: 100000,
      temperature: 0.3,
    },
    execution: {
      defaultMode: 'preview',
      maxRetries: 3,
      maxParallelTasks: 3,
      autoRollbackOnFailure: false,
      verifyStages: isFrontend
        ? ['lint', 'unit-test', 'e2e', 'coverage']
        : isBackend
          ? ['compile', 'lint', 'unit-test', 'integration-test', 'coverage']
          : ['compile', 'lint', 'unit-test', 'coverage'],
    },
    security: {
      sensitiveFiles: [
        '.env', '.env.*', 'credentials.*', '*.pem', '*secret*',
        'production*.yml', 'production*.yaml', 'id_rsa*', '*.key',
      ],
      dangerousCommands: [
        'rm -rf /', 'git push --force', 'DROP TABLE', 'DROP DATABASE',
        'chmod 777', ':(){ :|:& };:', '> /dev/sda',
      ],
      disabledRules: [],
      allowGitPush: false,
    },
    skills: {
      enabled: ['project-index', 'code-review', 'security-review'],
      autoGenerated: true,
    },
    memory: {
      maxProjectMemory: 10240,    // 10 MB
      maxGlobalMemory: 51200,     // 50 MB
      autoCompressThreshold: 50,  // compress after 50 tasks
    },
  };
}

export async function loadConfig(rootPath: string): Promise<ICloserConfig | null> {
  const projectConfigPath = path.join(rootPath, '.icloser', CONFIG_FILENAME);

  if (await fileExists(projectConfigPath)) {
    try {
      const raw = await readJson(projectConfigPath) as Record<string, unknown>;
      const projectRoot = (raw.project && typeof raw.project === 'object' ? (raw.project as any).rootPath : null) || rootPath;
      const identity = (raw.project && typeof raw.project === 'object' ? (raw.project as any).identity : null) || {};
      const defaults = defaultConfig(projectRoot, identity);
      const config = { ...defaults, ...raw } as ICloserConfig;
      // Merge with global config for AI settings: only inherit apiKey, never override project choices
      if (await fileExists(GLOBAL_CONFIG_PATH)) {
        try {
          const globalConfig = await readJson(GLOBAL_CONFIG_PATH);
          if (globalConfig.ai && !config.ai.apiKey) {
            const globalAI = globalConfig.ai as Partial<ICloserConfig['ai']>;
            if (globalAI.apiKey) {
              config.ai.apiKey = globalAI.apiKey;
            }
          }
        } catch { /* global config corrupt — skip */ }
      }
      return config;
    } catch { return null; } // corrupted project config
  }

  return null;
}

export async function saveConfig(config: ICloserConfig): Promise<void> {
  const configDir = path.join(config.project.rootPath, '.icloser');
  await ensureDir(configDir);
  const configPath = path.join(configDir, CONFIG_FILENAME);
  await writeJson(configPath, config);
}

export async function saveGlobalConfig(key: string, value: unknown): Promise<void> {
  await ensureDir(GLOBAL_CONFIG_DIR);
  let config: Record<string, unknown> = {};
  if (await fileExists(GLOBAL_CONFIG_PATH)) {
    config = await readJson(GLOBAL_CONFIG_PATH);
  }
  config[key] = value;
  await writeJson(GLOBAL_CONFIG_PATH, config);
}

export async function loadGlobalConfig(): Promise<Record<string, unknown>> {
  if (await fileExists(GLOBAL_CONFIG_PATH)) {
    return readJson(GLOBAL_CONFIG_PATH);
  }
  return {};
}

export function setAIProvider(config: ICloserConfig, provider: AIProvider, model?: string): ICloserConfig {
  config.ai.provider = provider;
  const defaultModels: Record<AIProvider, string> = {
    claude: 'claude-sonnet-4-6',
    deepseek: 'deepseek-v4-pro',
    openai: 'gpt-4o',
    qwen: 'qwen-max',
    mock: 'mock-offline',
  };
  config.ai.model = model || defaultModels[provider];
  return config;
}

export function toggleDefaultMode(config: ICloserConfig): ICloserConfig {
  config.execution.defaultMode =
    config.execution.defaultMode === 'preview' ? 'execute' : 'preview';
  return config;
}

export function setVerifyStages(config: ICloserConfig, stages: VerifyStage[]): ICloserConfig {
  config.execution.verifyStages = stages;
  return config;
}

export function addSensitiveFile(config: ICloserConfig, pattern: string): ICloserConfig {
  if (!config.security.sensitiveFiles.includes(pattern)) {
    config.security.sensitiveFiles.push(pattern);
  }
  return config;
}

export function disableSecurityRule(config: ICloserConfig, ruleId: string): ICloserConfig {
  config.security.disabledRules ||= [];
  if (!config.security.disabledRules.includes(ruleId)) {
    config.security.disabledRules.push(ruleId);
  }
  return config;
}

export function enableSecurityRule(config: ICloserConfig, ruleId: string): ICloserConfig {
  config.security.disabledRules ||= [];
  config.security.disabledRules = config.security.disabledRules.filter(id => id !== ruleId);
  return config;
}

export function enableSkill(config: ICloserConfig, skillName: string): ICloserConfig {
  if (!config.skills.enabled.includes(skillName)) {
    config.skills.enabled.push(skillName);
  }
  return config;
}

export function disableSkill(config: ICloserConfig, skillName: string): ICloserConfig {
  config.skills.enabled = config.skills.enabled.filter((s: string) => s !== skillName);
  return config;
}
